Major improvement to assertion failure output for trapInfo asserts
We now print the full trap info in the assertion message:
AssertionError: should not trap: didn't expect a trap here but got <TrapInfo #1: cause=<Cause COP2 (18)> capcause=<CapCause Tag_Violation (2)>, bdelay=False, capreg=6> (cap=<<t:0 s:0 perms:0x00000000 type:0x000000 offset:0x0001000000480206 base:0x0000000000000000 length:0xffffffffffffffff>>)